---
- name: Ping Server
  hosts: managed
  gather_facts: no
  vars_files:
    - ../vars_files/vars_print_vars.yaml 
  tasks:
    - name: Ping
      ping:
    
    - name: Print variable
      debug:
        msg: "{{message}}"